// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-19T09:04:30.689Z
// Source: TypeScript parser

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

import 'package:firela/parser/src/types.dart' show RawTransaction;

import './patterns/index.dart' show loadPatterns;
import './rules/index.dart' show loadRuleSet;
import './types.dart' show Confidence, PiiFinding, PiiPattern, RuleMode, RuleSet, SanitizeEngineOptions, SanitizeReport, SanitizeResult;

final Map<String, num> CONFIDENCE_ORDER = {'HIGH': 3, 'MEDIUM': 2, 'LOW': 1};

class SanitizeEngine {
  late final List<PiiPattern> patterns;
  late final String minConfidence;
  SanitizeEngine(dynamic regionOrOptions, [String? ruleMode]) {
    final opts = regionOrOptions is String ? {'region': regionOrOptions, 'ruleMode': ruleMode ?? 'regular'} : regionOrOptions;
    RuleSet ruleSet = loadRuleSet(opts.ruleMode);
    final regionPatterns = loadPatterns(opts.region);
    this.minConfidence = ruleSet.minConfidence ?? 'MEDIUM';
    this.patterns = regionPatterns.where((dynamic p) => ruleSet.maskCategories.contains(p.category) && (ruleSet.skipTypes ?? []).contains(p.type) == null).toList();
  }
  
  SanitizeResult sanitize(List<RawTransaction> transactions) {
    try {
    List<PiiFinding> findings = [];
    final sanitized = transactions.asMap().entries.map((entry) { final txn = entry.value; final idx = entry.key; return this.sanitizeTransaction(txn, idx, findings); }).toList();
    final report = SanitizeReport(totalScanned: transactions.length, totalSanitized: findings.where((dynamic f) => f.action == 'masked').toList().length, findings: findings);
    return SanitizeSuccess(success: true, data: sanitized, report: report);
    } catch (e) {
    final msg = e is Exception ? e.toString() : 'Unknown sanitize error';
    return SanitizeError(success: false, error: msg);
    }
  }
  
  RawTransaction sanitizeTransaction(RawTransaction txn, num index, List<PiiFinding> findings) {
    final fieldsToScan = [{'key': 'payee', 'value': txn.payee}, {'key': 'description', 'value': txn.description}];
    if (txn.metadata != null) {
    for (final entry in (txn.metadata as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final k = entry.key;
    final v = entry.value;
    if (v is String) {
    fieldsToScan.add({'key': 'metadata.$k', 'value': v});
    }
    }
    }
    if (txn.customFields != null) {
    for (final entry in (txn.customFields as Map<String, dynamic>).entries.map((e) => MapEntry(e.key, e.value)).toList()) {
    final k = entry.key;
    final v = entry.value;
    if (v is String) {
    fieldsToScan.add({'key': 'customFields.$k', 'value': v});
    }
    }
    }
    Map<String, dynamic> modified = {...(txn as Map<String, dynamic>)};
    for (final _item in fieldsToScan) {
    final key = _item['key']!;
    final value = _item['value']!;
    if (value.isEmpty) {
    continue;
    }
    final _obj = this.scanField(value);
    final result = _obj.result;
    final fieldFindings = _obj.fieldFindings;
    if (fieldFindings.isNotEmpty) {
    this.setField(modified, key, result);
    findings.addAll(fieldFindings.map((dynamic f) => ({'transactionIndex': index, 'field': key, 'piiType': f.type, 'confidence': f.confidence, 'action': f.action})).toList());
    }
    }
    return ((modified as dynamic) as RawTransaction);
  }
  
  dynamic scanField(String value) {
    var result = value;
    dynamic fieldFindings = [];
    for (final piiPattern in this.patterns) {
    result = result.replaceAllMapped(piiPattern.pattern, (Match m) { final match = m.group(0)!; String confidence;
    if (piiPattern.validator != null) {
    confidence = piiPattern.validator(match) != null ? 'HIGH' : 'LOW';
    } else {
    confidence = 'MEDIUM';
    }
    final meetsThreshold = CONFIDENCE_ORDER[confidence]!! >= CONFIDENCE_ORDER[this.minConfidence]!!;
    if (meetsThreshold != null) {
    fieldFindings.add({'type': piiPattern.type, 'confidence': confidence, 'action': 'masked'});
    return piiPattern.mask(match);
    } else {
    fieldFindings.add({'type': piiPattern.type, 'confidence': confidence, 'action': 'kept'});
    return match;
    } });
    }
    return {'result': result, 'fieldFindings': fieldFindings};
  }
  
  void setField(Map<String, dynamic> obj, String keyPath, String value) {
    if (keyPath == 'payee') {
    // TODO: obj.payee = value; // final field assignment — restructure to pass via constructor
    } else if (keyPath == 'description') {
    // TODO: obj.description = value; // final field assignment — restructure to pass via constructor
    } else if (keyPath.startsWith('metadata.')) {
    final metaKey = keyPath.substring('metadata.'.length);
    // TODO: obj.metadata = {...((obj['metadata']! as Map<String, dynamic>)), metaKey: value}; // final field assignment — restructure to pass via constructor
    } else if (keyPath.startsWith('customFields.')) {
    final cfKey = keyPath.substring('customFields.'.length);
    // TODO: obj.customFields = {...((obj['customFields']! as Map<String, dynamic>)), cfKey: value}; // final field assignment — restructure to pass via constructor
    }
  }
  
}
