// AUTO-GENERATED BY ts2dart - DO NOT EDIT MANUALLY
// Generated: 2026-04-17T11:09:30.446Z
// Source: TypeScript parser
// Parser: sanitizer

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_unused_element
// ignore_for_file: unused_local_variable

final SANITIZER_VERSION = '0.1.0';
